apiVersion: v1
kind: Service
metadata:
  name: bentra-mcp
  namespace: bentra-mcp
spec:
  type: ClusterIP
  selector:
    app: bentra-mcp
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
