apiVersion: v1
kind: LimitRange
metadata:
  name: github-runners-limits
  namespace: github-runners
spec:
  limits:
  - type: Container
    min:
      cpu: 100m
      memory: 256Mi
    max:
      cpu: "2"
      memory: 6Gi
    default:
      cpu: 500m
      memory: 1Gi
    defaultRequest:
      cpu: 250m
      memory: 512Mi
