apiVersion: v1
kind: Secret
metadata:
    name: github-runner-secrets
    namespace: github-runners
type: Opaque
stringData:
    GITHUB_TOKEN: ENC[AES256_GCM,data:PAR4mHKj7ihUO91WwCa8amE/LBtgXkt/AkHNrZkp3TOT8O1ert9ukA==,iv:lnGXa++Bycb9liiDKVzxncSMGk0bU9b/SrxRRkDdmB0=,tag:uiO9XY0iEbleXJHSu2sWIA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxaS9QMzIwekpWUjgwQjRj
            MWprUWM3MnpjRWxid0c0NXB6a2JPMVhybTM4Ck1MMmZCQVhLUU5nUXpDaE1heVR6
            OFRnOUc0NytxbjRPLzBmWHNSemg4T3cKLS0tIG5jZGt1T3NPZVVKZ0ZYNkl2d0NC
            ZHMxcEY1YmdpN2hnVmdvUVVReXNpemsKtyyp2UxdTNUBF+DSz+C4OsNQstwyrSCy
            BJmkF3A6vEeK9/va27gbnnTnE9r3y8KGaexHIvpVLcJqhfq9uQr3Jg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17jcytaggapk20sqsy5azsz7t49jlfqreqjflhze2c92chy7hhegqdvdyl8
    encrypted_regex: ^(stringData|data)$
    lastmodified: "2026-07-16T02:06:13Z"
    mac: ENC[AES256_GCM,data:bqJ4Nu3tY5VYL4jgy9VP7AKtTA5hTmdve+wm9hhdPm2KCeYjjP7sl0hBDB3to2vQN6bvy/4A/8KcdDUvMF6VJrjl3xsGHNS+a8BIGYvgaW8fA03mwmsWm8R0SFITphIVYJIhuQJfAo3HV1Tj94jb5VChrBGOQLzNtGCdIOWC3aY=,iv:FyaevO+Z4NB3Ao04pe7YHrbJpCodKYvTqaEIqmt/v1o=,tag:mAv+S1ZZ/pO2FGEgNdZDEw==,type:str]
    version: 3.13.2
