apiVersion: v1
kind: Secret
metadata:
    name: github-runner-secrets
    namespace: github-runners
type: Opaque
stringData:
    GITHUB_TOKEN: ENC[AES256_GCM,data:GJlaVBck8ObsZJMa8xR+MCysgkg=,iv:5LbZKvaGlNVj5TyIhQlkLDH+Jg4XNPlijolvQPJwbds=,tag:G6t/soXFvm/VTGBVLuaR5A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxaS9QMzIwekpWUjgwQjRj
            MWprUWM3MnpjRWxid0c0NXB6a2JPMVhybTM4Ck1MMmZCQVhLUU5nUXpDaE1heVR6
            OFRnOUc0NytxbjRPLzBmWHNSemg4T3cKLS0tIG5jZGt1T3NPZVVKZ0ZYNkl2d0NC
            ZHMxcEY1YmdpN2hnVmdvUVVReXNpemsKtyyp2UxdTNUBF+DSz+C4OsNQstwyrSCy
            BJmkF3A6vEeK9/va27gbnnTnE9r3y8KGaexHIvpVLcJqhfq9uQr3Jg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17jcytaggapk20sqsy5azsz7t49jlfqreqjflhze2c92chy7hhegqdvdyl8
    encrypted_regex: ^(stringData|data)$
    lastmodified: "2026-07-15T23:20:05Z"
    mac: ENC[AES256_GCM,data:OGDXMyAE0Q0JxJuu6o2tLyVVM29usANHSiRw5U3iXW0nRQS++WsTnl1RHJPbb3nkyNphpwdIzPNaYfSOeaRYMPjPFOY2FOx9wqkGFfzIX2GTLDpsmAa22yFCEpM8MdH3Q5G+jn9WAufyo489Oi3wq84uIn+czbhctqQTkwDmgA4=,iv:RNDk8wPDaKOSi8/CkHsleDcwitta2ZLHDEI10sARVls=,tag:vLYUHscXsVfhfkVCruaHJw==,type:str]
    version: 3.13.2
